### ISSUE TITLE
Parallelism: xargs

### ISSUE THREAD

**Issue by ax3l** [azet/community_bash_style_guide#10]
Hi and thanks for the great writeup :sparkles: 

In the section "Basic parallelism" I missed `xargs` a little. It's pretty straight forward and I use it quite a lot for basic parallelism. Is this intentionally or are PRs adding one or two sentences about it welcome? :)

example: repack all hdf5 files in a directory with 64 processes in parallel

``` bash
find ${dirName} -name "*.h5" | xargs -n1 -P64 -I{} \
        sh -c 'echo "compress $1 ..." &&   \
               h5repack -i $1 -o $1.gz -f GZIP=1 && mv $1.gz $1' _ {}
```

**Comment by azet** [comment]
You're right. I'm happy taking PRs for that.

**Comment by azet** [comment]
@ax3l ping?
