### ISSUE TITLE
bash Style Or POSIX Shell Style?

### ISSUE THREAD

**Issue by ldo** [azet/community_bash_style_guide#13]
Is this a style guide specific to bash, or is it for POSIX shells generally? Many of the tips seem to be bash-specific (e.g. use built-in expressions instead of `expr`), but then you say don’t use backticks because they may not work with some non-bash shell.

Maybe separate out the bash-specific tips from the non-bash-specific ones?

**Comment by azet** [comment]
it says `community bash style guide`, does that answer your question? :)
