### ISSUE TITLE
bash script for creating eot (zero byte) file for all the folder coming in (getting copied)

### ISSUE THREAD

**Issue by rashidinfo** [azet/community_bash_style_guide#15]
Can anyone help me creating Bash script for creating eot (zero byte) file for all the folder coming (getting copied) into the Linux centOs.

Suggestion:
1.> script need to understand if the folder is been completely copied 
2.>Create a file name "folder.eot" (zero byte) in the same place

Response Required, Thanks.

**Comment by azet** [comment]
This is best for stackexchange or stackoverflow. Not the issue tracker of an open source project that maintains a Bash style guide. 

Try asking your questions politely over here:
1. https://stackoverflow.com/questions/tagged/bash
2. https://unix.stackexchange.com/questions/tagged/bash

I'm closing this issue as it's a question unrelated to this project.
