### ISSUE TITLE
Iterate a range of numbers defined by a variable

### ISSUE THREAD

**Issue by denaitre** [azet/community_bash_style_guide#8]
Hello,

First of all thanks for this nice repo :+1: 

In the ["do not use seq"](https://github.com/azet/community_bash_style_guide#do-not-use-seq-for-ranges) part you recommend to use the bash built-in range expression which is not straightforward compatible with variables since it works with literals.

Then, is there a best option ? || which of those two options is the best:
* use the external `seq` such as: `for i in seq 1 ${END}; do`;
* use bash built-ins `eval` and `echo` such as: `for i in $(eval echo "{1..$END}"); do` but requires a `fork()` for substitution.

**Comment by azet** [comment]
Hi @denaitre,

Thanks for your feedback.

As far as I understand it's possible to use brace expansion for these: http://wiki.bash-hackers.org/syntax/expansion/brace

I'm currently very busy. Would you mind opening a pull request with your suggested changes?

**Comment by azet** [comment]
any update?
